name = "ArtificialLandscapes"
uuid = "9fcb4f73-e569-4ec8-8885-6d676206011b"
authors = ["NicolasL-S <nicolas.lepagesaucier@gmail.com> and contributors"]
version = "0.1.0"

[deps]
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
FastPow = "c0e83750-1142-43a8-81cf-6c956b72b4d1"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"

[compat]
CSV = "0.10.15"
DataFrames = "1.7.0"
FastPow = "0.1.0"
LinearAlgebra = "1.11.0"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
