name = "ArtificialLandscapes"
uuid = "9fcb4f73-e569-4ec8-8885-6d676206011b"
authors = ["NicolasL-S <nicolas.lepagesaucier@gmail.com> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
